### ISSUE TITLE
Outdated powercord API usage

### ISSUE THREAD

**Issue by SinnerK0N** [cloudrac3r/powercord-server-info#5]
Basically the title
This made the plugin crash right after loading

I made a PR with fix: [https://github.com/cloudrac3r/powercord-server-info/pull/4](https://github.com/cloudrac3r/powercord-server-info/pull/4)

**Comment by cloudrac3r** [comment]
I no longer maintain this plugin since I left powercord in late 2019 and deleted my discord account in mid 2020. You should use your own fork instead.
